"""Request and response schemas for chat-related endpoints."""

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request body used by the chat endpoint."""

    message: str = Field(..., min_length=1, description="User message sent to the model.")
    system_prompt: str | None = Field(
        default=None,
        description="Optional system prompt override for the current request.",
    )


class ChatResponse(BaseModel):
    """Response body returned by the chat endpoint."""

    reply: str = Field(..., description="Assistant reply generated by the model.")
    model: str = Field(..., description="Model name used for the response.")
    provider: str = Field(..., description="Logical provider type used by the service.")
